#Common taks are kept in common role to call when erver required.



- name: Creat roboshop user
  ansible.builtin.user: #Ansible user module
    name: roboshop

- name: Remove app directory
  ansible.builtin.file: #Ansible file module
    path: /app
    state: absent

- name: Creat app directory
  ansible.builtin.file: #Ansible file module
    path: /app
    state: directory

# - name: Download the application code to created app directory.
#   ansible.builtin.get_url: #Ansible get url module
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: /tmp
  
# - name: Unzip
#   ansible.builtin.unarchive: #Ansible unzip module
#     src: "/tmp/{{component}}.zip"
#     dest: /app
#     remote_src: yes

#Commented the above lines because the above one is downloading the code from S3
- name: Download artifact from nexus
  ansible.builtin.get_url:
    url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: /tmp

- name: "extract {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes