# - name: "Copy the {{component}} file"
#   ansible.builtin.copy:  #Search "ansible copy module" in google to find the modules
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

- name: "Copy the {{component}} file"
  ansible.builtin.template:  #ansible template module simlar to "ansible copy module" 
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service"

- name: Daemon reload
  ansible.builtin.systemd_service:  #Ansible systectl module
    daemon_reload: true

- name: "Start & Enable {{component}} Service"
  ansible.builtin.service: 
    name: "{{component}}"
    state: started
    enabled: yes 